### ISSUE TITLE
Error: "hello_world" is translated here but not found in default locale [ExtraTranslation] (klint issues)

### ISSUE THREAD

**Issue by RdeWilde** [joreilly/PeopleInSpace#66] opened 2021-07-21 20:11 UTC
> > Task :wearApp:lintDebug FAILED
> Wrote HTML report to file:///Users/Robert/projects/core/wearApp/build/reports/lint-results-debug.html
> Lint found 1 error and 2 warnings. First failure:
> /Users/Robert/projects/core/wearApp/src/main/res/values-round/strings.xml:2: Error: "hello_world" is translated here but not found in default locale [ExtraTranslation]
>     <string name="hello_world">Hello Round World!</string>

When trying to compile the wearApp from Android studio, i get this lint error.

![Schermafbeelding 2021-07-21 om 22 09 56](https://user-images.githubusercontent.com/184016/126553451-389f1c91-243a-4927-95a2-42ec894c833d.png)

I'll try to look for a solution. Can't be hard to the sound of it.

**Comment by RdeWilde** [comment] 2021-07-21 20:29
Here's two: https://www.programmersought.com/article/18483584747/ 

I prefer the second one. So I added it to wearApp/build.gradle.kts in the 'android' section:
```
    lint {
        disable("ExtraTranslation")
    }
```

While we are at it, it gave me some more errors.

```
wearApp/src/main/java/com/surrus/peopleinspace/MainActivity.kt:8:1: Lint error > [no-wildcard-imports] Wildcard import
wearApp/src/main/java/com/surrus/peopleinspace/MainActivity.kt:11:1: Lint error > [no-wildcard-imports] Wildcard import
wearApp/src/main/java/com/surrus/peopleinspace/MainActivity.kt:35:1: Lint error > [no-blank-line-before-rbrace] Unexpected blank line(s) before "}"
wearApp/src/main/java/com/surrus/peopleinspace/MainActivity.kt:39:1: Lint error > [no-blank-line-before-rbrace] Unexpected blank line(s) before "}"
wearApp/src/main/java/com/surrus/peopleinspace/MainActivity.kt:63:1: Lint error > [no-consecutive-blank-lines] Needless blank line(s)
```
Will ook into it.

**Comment by RdeWilde** [comment] 2021-07-21 21:25
Okay, well, this worked for wearApp, but there's so much more wildcard imports and other linter stuff, this is getting annoying very vast.

Maybe it is easier to disable the rule by creating an .editorconfig

**Comment by joreilly** [comment] 2021-07-21 21:47
Just to clarify....are these issues that are cropping now with new RC version of AS Arctic Fox?

**Comment by joreilly** [comment] 2021-07-22 20:13
Am mostly way from laptop this week.....these are failure you get if you explicitly run lint?  Are you seeing issue for example if you run app in AS?  I run basic build/test runs as part of GH workflow but not running lint right now.

**Comment by joreilly** [comment] 2021-07-22 20:15
Sorry, just noticed the "When trying to compile the wearApp from Android studio, i get this lint error" comment above....not sure why I wasn't seeing that here....

**Comment by joreilly** [comment] 2021-07-22 20:22
So, I did try to run wear app here just now (still in beta 5) and ran in to another issue at runtime caused by recent refactoring....just pushed fix for that.

**Comment by RdeWilde** [comment] 2021-07-22 20:24
Yeah, just when I hit 'build'. It also triggers errors on the 'generated' folders (sqldelight db models).

For now I try to disable some rules and exclude directories based on documentation here: https://github.com/jeremymailen/kotlinter-gradle
I'll draft a PR if it works right.

Btw, take your time. I'm just reporting everything I run into, so that it can be helpfull for others. I'm not on any timeline.

**Comment by RdeWilde** [comment] 2021-07-22 21:25
It seems like the `exclude`-filter is not matching the full path, and so you can not match for `**/generated/**`.

This is what I use now in common-subproject. Probably there's a more generic way to configure it, but it works for now:
```
kotlinter {
    disabledRules = arrayOf("no-wildcard-imports")
}

tasks.withType(org.jmailen.gradle.kotlinter.tasks.LintTask::class) {
    exclude("/com/surrus/peopleinspace/db/**")
}
```

**Comment by joreilly** [comment] 2021-07-23 08:54
I pushed original issue reported here (at least indirectly) by removing that string....wasn't actually needed in project.

**Comment by joreilly** [comment] 2021-07-23 16:24
@RdeWilde are you still seeing lint issues for main `app` module?  I'm not see any here for example if I run for example `./gradlew :app:lintDebug` (but again I'm not on AS RC version yet if that's a factor)

**Closed** 2023-02-18 18:18 UTC
