### ISSUE TITLE
project import failed in a newly installed AS 4.2 canary 8

### ISSUE THREAD

**Issue by odifek** [joreilly/PeopleInSpace#8] opened 2020-08-31 21:36 UTC
Project import fails with error `Please initialize at least one Kotlin target in 'common (:common)'.`

OS: Ubuntu Linux 20.04

Android Studio Version: 4.2 Canary 8. (No multiplatform project has been done before now)

Clicking Run with --debug option returns this error. `Caused by: org.gradle.internal.component.AmbiguousConfigurationSelectionException: The consumer was configured to find a runtime of a library compatible with Java 14, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'. However we cannot choose between the following variants of project :common:
`
Changing the default system jdk to java 8 prints the same message but now Java 8 instead of Java 14.

**Comment by joreilly** [comment] 2020-09-01 07:09
I've tried importing it that way and also separately cloning and then opening project and haven't been able to reproduce yet (with same version of AS).  Not sure if anyone else reading this has tried this on Linux (in case somehow that's a factor?)

**Comment by VeryRoadTrip** [comment] 2020-09-01 14:27
I have the same problem:

**Comment by joreilly** [comment] 2020-09-01 14:31
@VeryRoadTrip is this also on linux?  Just to also confirm you are using 4.2 Canary version as well?  Lastly, have you been able to open other Kotlin Multiplatform project successfully?

**Comment by joreilly** [comment] 2020-09-01 14:43
@odifek @VeryRoadTrip if you haven't already, can you also try to open another Kotlin Multiplatform project and see if you're having same issue (e.g. https://github.com/touchlab/KaMPKit)

**Comment by joreilly** [comment] 2020-09-01 14:53
I asked in slack and @arkivanov mentioned he had seen same issue during migration to Kotlin 1.4 due to

```
js {
        browser {
        }
    }
```

Following as his fix.... @odifek @VeryRoadTrip could one of you check if this fixes issue for you (and perhaps open PR with fix :) )

https://github.com/arkivanov/MVIKotlin/blob/41a47c0fb022bc79312053d7605f83a02e1b5df7/sample/todo-app-js/build.gradle.kts#L47

**Comment by arkivanov** [comment] 2020-09-01 16:01
@joreilly Just tried by myself. The error is there, the suggested fix does not help.

**Comment by odifek** [comment] 2020-09-01 16:33
I found this issue opened by Zac Swears. But I am not yet able to make sense of the discussion. https://github.com/gradle/gradle/issues/12126

**Comment by joreilly** [comment] 2020-09-01 16:36
@arkivanov believes issue might be related to cocoapods plugin.  @odifek @VeryRoadTrip could you try opening https://github.com/touchlab/KaMPKit and see if you see same issue (it also uses that plugin)

**Comment by arkivanov** [comment] 2020-09-01 17:09
@joreilly KaMPKit opens fine. But it uses another plugin: `co.touchlab.native.cocoapods`

**Comment by odifek** [comment] 2020-09-01 20:14
That's correct. KaMPKit runs fine on my system also

**Comment by joreilly** [comment] 2020-09-18 08:56
alpha11 just out....just in case this somehow resolves this issue?

**Comment by martinbonnin** [comment] 2020-09-27 22:19
For what it's worth, I can synchronize correctly with AGP `4.2.0-alpha12`

**Comment by darran-kelinske-fivestars** [comment] 2020-11-19 18:59
I am having the same issue on canary - i can build the web browser target using gradle, but the android build.gradle.kts is not being recognized.

**Comment by joreilly** [comment] 2020-11-19 19:24
@darran-kelinske-fivestars is this also on linux?

**Comment by darran-kelinske-fivestars** [comment] 2020-11-19 19:25
yes sir - on the latest ubuntu - tried java 8 and 11 as the project sdk

**Comment by joreilly** [comment] 2020-11-19 19:28
Unfortunately I don't have a linux setup to test this on....if anyone here is able to diagnose and create PR that would be great

**Comment by darran-kelinske-fivestars** [comment] 2020-11-19 19:32
what OS are you running?

**Comment by joreilly** [comment] 2020-11-19 19:32
macOS

**Comment by dazza5000** [comment] 2020-11-20 13:25
This fixed it for me on Ubuntu https://github.com/joreilly/PeopleInSpace/pull/14

**Comment by joreilly** [comment] 2020-11-22 17:20
Curious if other folks that reported issues here using linux are seeing this resolved using canary 16 version?

**Comment by darran-kelinske-fivestars** [comment] 2020-11-25 12:56
@odifek - any luck for you?

**Comment by odifek** [comment] 2020-11-25 16:07
@darran-kelinske-fivestars yea. Works fine now on latest canary versions

**Comment by joreilly** [comment] 2020-12-04 18:38
ok, going to close this for now and we can reopen if the issue resurfaces

**Closed by joreilly** 2020-12-04 18:38 UTC
